### ISSUE TITLE
Loader takes too long to load on mobile & desktop

### ISSUE THREAD

**Issue by demonkillerr** [tcet-opensource/ieee-website#3]
The loader is taking a lot of time. It is advisable to remove the loader

**Comment by bhumikadubey** [comment]
I would like to work on this can you assign it to me?

**Comment by real-coder007Ravi** [comment]
@demonkillerr Could you please assign it to me

**Comment by real-coder007Ravi** [comment]
Under Hactoberfest 2023 label

**Comment by demonkillerr** [comment]
feel free to file a PR

**Comment by AtharvaTanpure18** [comment]
Solved
